noun = input("Here is a [noun] ")
adj = input("Who is very [adj] ")
verb = input("Who likes to [verb] along the road ")
noun2 = input("His friend [noun2] ")
adj2 = input("He is feeling [adj2] ")
verb2 = input("So he tried to [verb2] ")
noun3 = input("[noun2]'s pet is named [noun3] ")
adj3 = input("It is a dog with [adj3] fur ")
verb3 = input("It likes to [verb3] on the carpet ")
noun4 = input("[noun2] wanted to go to the [noun4]")
adj4 = input("[noun4] is a very [adj4] place")
verb4 = input("so [noun2] was hoping to [verb4] there.")
noun5 = input("They met [noun5] there.")
adj5 = input("[noun5] was strangely [adj5]")
verb5 = input("as he [verb5] in the distance")

print(f"Here is a {noun}.  Who is very {adj}.  Who likes to {verb} along the road.")
print(f"His friend {noun2} is feeling {adj2}, so he tried to {verb2}.")
print(f"{noun2}'s pet named {noun3} is a dog with {adj3} fur.  It likes to {verb3} on the carpet.")
print(f"{noun2} wanted to go to the {noun4}.  {noun4} is a very {adj4} place, so {noun2} was hoping to {verb4} there.")
print(f"They met {noun5} there.  {noun5} was strangely {adj5} as he {verb5} in the distance" )
